name: CI -> Deploy to My website
on:
  push:
    branches: [ master, Development ]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: "172.16.0.7"
          user: "jlwilliamson"
          #password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./public_html"
          delete: "false"
